data:
  train_path: data/raw/train.csv
  test_path: data/raw/test.csv

base:
  RANDOM_SEED: 20

modeling:
  TARGET_COLUMN: 'SalePrice'
  VALID_SIZE: 0.2

hyperparameters:
  ALPHA_RIDGE: [0.1, 1.0, 10.0]
  ALPHA_LASSO: [0.001, 0.01, 0.1]
  ELASTICNET_L1_RATIO: 0.5